version: '3.0'
services:
  db:
    image: mariadb:10.4
    volumes:
      - mysql-data:/var/lib/mysql
      - ./image-files/db/phpmyadmin_init.sql:/docker-entrypoint-initdb.d/00-pma_init.sql:ro
      - ./image-files/db/concrete5_init.sql:/docker-entrypoint-initdb.d/01-concrete5_init.sql:ro
    restart: always
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./image-files/phpmyadmin/phpmyadmin_config.php:/etc/phpmyadmin/config.user.inc.php:ro
    depends_on:
      - db
  web:
    image: yiisoftware/yii2-php:${PHP_VERSION}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./src:/app/
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./php.ini:/usr/local/etc/php/conf.d/zz-custom.php.ini
    env_file:
      - .env
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local